#!/usr/bin/env python3
"""Generate flattened AXLE Lean bundles from repo-local Lean modules.

The durable Lean source of truth is the imported Lake module surface under
formal/lean. AXLE can still benefit from standalone bundles, but those bundles
should be generated from the module graph rather than hand-maintained.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LEAN_ROOT = REPO_ROOT / "formal" / "lean"
LOCAL_MODULE_PREFIXES = ("Core.", "Theorems.")
IMPORT_RE = re.compile(r"^import\s+([A-Za-z0-9_.'/-]+)\s*$")


class BundleError(Exception):
    pass


def module_to_path(module: str) -> Path:
    return LEAN_ROOT / Path(*module.split(".")).with_suffix(".lean")


def path_to_module(path: Path) -> str:
    rel = path.resolve().relative_to(LEAN_ROOT.resolve())
    return ".".join(rel.with_suffix("").parts)


def is_local_module(module: str) -> bool:
    return module.startswith(LOCAL_MODULE_PREFIXES)


def read_module(module: str) -> str:
    path = module_to_path(module)
    if not path.exists():
        raise BundleError(f"local module not found: {module} -> {path}")
    return path.read_text(encoding="utf-8")


def parse_imports(content: str) -> tuple[list[str], list[str]]:
    local_imports: list[str] = []
    external_imports: list[str] = []
    for line in content.splitlines():
        match = IMPORT_RE.match(line.strip())
        if not match:
            continue
        module = match.group(1)
        if is_local_module(module):
            local_imports.append(module)
        else:
            external_imports.append(module)
    return local_imports, external_imports


def strip_local_imports(content: str) -> str:
    output: list[str] = []
    for line in content.splitlines():
        match = IMPORT_RE.match(line.strip())
        if match and is_local_module(match.group(1)):
            continue
        output.append(line)
    return "\n".join(output).strip() + "\n"


def collect_modules(
    module: str,
    seen: set[str],
    visiting: set[str],
    ordered: list[str],
) -> None:
    if module in seen:
        return
    if module in visiting:
        chain = " -> ".join([*visiting, module])
        raise BundleError(f"cyclic local imports: {chain}")

    visiting.add(module)
    content = read_module(module)
    local_imports, _external_imports = parse_imports(content)
    for imported in local_imports:
        collect_modules(imported, seen, visiting, ordered)
    visiting.remove(module)
    seen.add(module)
    ordered.append(module)


def generate_bundle(target_module: str) -> str:
    ordered: list[str] = []
    collect_modules(target_module, set(), set(), ordered)

    external_imports: list[str] = []
    body_parts: list[str] = []
    for module in ordered:
        content = read_module(module)
        _local, external = parse_imports(content)
        for imported in external:
            if imported not in external_imports:
                external_imports.append(imported)
        body_parts.append(
            "\n".join(
                [
                    f"/- BEGIN GENERATED MODULE: {module} -/",
                    strip_local_imports(content).rstrip(),
                    f"/- END GENERATED MODULE: {module} -/",
                ]
            )
        )

    header = [
        "/-",
        "  GENERATED FILE. Do not edit by hand.",
        "",
        f"  Source module: {target_module}",
        "  Generated by: scripts/generate_axle_bundle.py",
        "",
        "  Purpose: standalone AXLE submission bundle with repo-local imports",
        "  recursively inlined.",
        "-/",
        "",
    ]

    imports = [f"import {module}" for module in external_imports]
    if imports:
        header.extend(imports)
        header.append("")

    return "\n".join(header + body_parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", help="Target Lean module or path under formal/lean")
    parser.add_argument("output", type=Path, help="Output bundle path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if output differs from generated content; do not write",
    )
    args = parser.parse_args()

    try:
        target = args.target
        if target.endswith(".lean") or "/" in target or "\\" in target:
            target_path = Path(target)
            if not target_path.is_absolute():
                target_path = (REPO_ROOT / target_path).resolve()
            target = path_to_module(target_path)

        generated = generate_bundle(target)
        output = args.output
        if not output.is_absolute():
            output = (REPO_ROOT / output).resolve()

        if args.check:
            if not output.exists():
                print(f"FAIL bundle missing: {output}", file=sys.stderr)
                return 1
            current = output.read_text(encoding="utf-8")
            if current != generated:
                print(f"FAIL bundle drift: {output}", file=sys.stderr)
                return 1
            print(f"PASS bundle current: {output}")
            return 0

        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(generated, encoding="utf-8", newline="\n")
        print(f"WROTE {output}")
        return 0
    except BundleError as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
