/-
  GENERATED FILE. Do not edit by hand.

  Source module: Core.CrossRecordRoute
  Generated by: scripts/generate_axle_bundle.py

  Purpose: standalone AXLE submission bundle with repo-local imports
  recursively inlined.
-/

/- BEGIN GENERATED MODULE: Core.IntegratedLicense -/
/-
  Formal Symbolic Systems Theory - Integrated license core.

  Status: candidate integration slice / stage 1 / do not promote.

  Source prose:
    docs/formation/compiler_records/1c_project_artifact_records_v0.1.json

  Purpose:
    Encode the dependency chain pressured by the 1C project-artifact pilot:

      persistent system -> use episode -> recognition/standing -> policy license

    This file is intentionally abstract. It composes the previously discovered
    predicate surfaces without importing or collapsing their richer local
    structures.

  Non-claims:
    1. No domain-specific account of valid systems, standing, or policy.
    2. No claim that formal integration proves empirical warrant.
    3. No collapse of object, event, standing, and norm into one ontology.
    4. No production compiler/runtime claim.
-/

namespace FSST

universe u

structure IntegratedWorld where
  SymbolicSystem : Type u
  SymbolicUse : Type u
  Recognizer : Type u
  Consequence : Type u
  SystemUse :
    SymbolicSystem ->
    SymbolicUse ->
    Prop
  AuthorityLicensed :
    SymbolicUse ->
    Recognizer ->
    Prop
  PolicyLicensed :
    SymbolicUse ->
    Consequence ->
    Prop
  ConsequenceDrawn :
    SymbolicUse ->
    Consequence ->
    Prop

namespace IntegratedWorld

variable (W : IntegratedWorld)

def FullyLicensed
    (system : W.SymbolicSystem)
    (use : W.SymbolicUse)
    (recognizer : W.Recognizer)
    (consequence : W.Consequence) : Prop :=
  W.SystemUse system use /\
    W.AuthorityLicensed use recognizer /\
    W.PolicyLicensed use consequence

variable {W}

def FullyUnauthorized
    (system : W.SymbolicSystem)
    (use : W.SymbolicUse)
    (recognizer : W.Recognizer)
    (consequence : W.Consequence) : Prop :=
  W.ConsequenceDrawn use consequence /\
    Not (FullyLicensed W system use recognizer consequence)

theorem full_license_requires_system_use
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (h : FullyLicensed W system use recognizer consequence) :
    W.SystemUse system use := by
  exact h.left

theorem full_license_requires_authority_license
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (h : FullyLicensed W system use recognizer consequence) :
    W.AuthorityLicensed use recognizer := by
  exact h.right.left

theorem full_license_requires_policy_license
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (h : FullyLicensed W system use recognizer consequence) :
    W.PolicyLicensed use consequence := by
  exact h.right.right

theorem no_system_use_blocks_full_license
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hnot : Not (W.SystemUse system use)) :
    Not (FullyLicensed W system use recognizer consequence) := by
  intro hlicensed
  exact hnot hlicensed.left

theorem no_authority_blocks_full_license
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hnot : Not (W.AuthorityLicensed use recognizer)) :
    Not (FullyLicensed W system use recognizer consequence) := by
  intro hlicensed
  exact hnot hlicensed.right.left

theorem no_policy_blocks_full_license
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hnot : Not (W.PolicyLicensed use consequence)) :
    Not (FullyLicensed W system use recognizer consequence) := by
  intro hlicensed
  exact hnot hlicensed.right.right

theorem drawn_without_system_use_is_fully_unauthorized
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hdrawn : W.ConsequenceDrawn use consequence)
    (hnot : Not (W.SystemUse system use)) :
    FullyUnauthorized system use recognizer consequence := by
  exact And.intro hdrawn (no_system_use_blocks_full_license hnot)

theorem drawn_without_authority_is_fully_unauthorized
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hdrawn : W.ConsequenceDrawn use consequence)
    (hnot : Not (W.AuthorityLicensed use recognizer)) :
    FullyUnauthorized system use recognizer consequence := by
  exact And.intro hdrawn (no_authority_blocks_full_license hnot)

theorem drawn_without_policy_is_fully_unauthorized
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (hdrawn : W.ConsequenceDrawn use consequence)
    (hnot : Not (W.PolicyLicensed use consequence)) :
    FullyUnauthorized system use recognizer consequence := by
  exact And.intro hdrawn (no_policy_blocks_full_license hnot)

theorem full_unauthorized_has_drawn_unlicensed
    {system : W.SymbolicSystem}
    {use : W.SymbolicUse}
    {recognizer : W.Recognizer}
    {consequence : W.Consequence}
    (h : FullyUnauthorized system use recognizer consequence) :
    W.ConsequenceDrawn use consequence /\
      Not (FullyLicensed W system use recognizer consequence) := by
  exact h

end IntegratedWorld

end FSST
/- END GENERATED MODULE: Core.IntegratedLicense -/
/- BEGIN GENERATED MODULE: Core.RouteLicensed -/
/-
  Formal Symbolic Systems Theory - Route-licensed consequence core.

  Status: candidate module-composition slice / stage 1 / do not promote.

  Source pressure:
    docs/formation/30_partial_standing_restricted_license_batch_v0.1.md

  Purpose:
    Encode the route-level invariant discovered by the 1K partial-standing
    batch: a consequence route is licensed only when every recognizer in the
    route has ordinary full license for the system/use/consequence and also
    has standing that covers that specific consequence.

    This file intentionally composes the earlier integrated license surface:

      IntegratedWorld.FullyLicensed

    The one new predicate is consequence-specific standing:

      ConsequenceStanding use recognizer consequence

  Non-claims:
    1. No domain-specific account of what grants standing.
    2. No claim that route licensing proves moral or political legitimacy.
    3. No production compiler/runtime claim.
    4. No claim that local Lean project import architecture is finalized.
-/


namespace FSST

universe u

structure RouteLicenseWorld where
  integrated : IntegratedWorld
  ConsequenceStanding :
    integrated.SymbolicUse ->
    integrated.Recognizer ->
    integrated.Consequence ->
    Prop

namespace RouteLicenseWorld

variable (W : RouteLicenseWorld)

structure ConsequenceRoute where
  system : W.integrated.SymbolicSystem
  use : W.integrated.SymbolicUse
  consequence : W.integrated.Consequence
  recognizer_chain : List W.integrated.Recognizer

def RouteLicensed
    (route : ConsequenceRoute W) : Prop :=
  W.integrated.SystemUse route.system route.use /\
    W.integrated.PolicyLicensed route.use route.consequence /\
    forall recognizer,
      recognizer ∈ route.recognizer_chain ->
        W.integrated.AuthorityLicensed route.use recognizer /\
          W.ConsequenceStanding route.use recognizer route.consequence

variable {W}

def RouteConsequenceDrawn
    (route : ConsequenceRoute W) : Prop :=
  W.integrated.ConsequenceDrawn route.use route.consequence

def RouteUnauthorized
    (route : ConsequenceRoute W) : Prop :=
  RouteConsequenceDrawn route /\
    Not (RouteLicensed W route)

theorem route_license_requires_system_use
    {route : ConsequenceRoute W}
    (h : RouteLicensed W route) :
    W.integrated.SystemUse route.system route.use := by
  exact h.left

theorem route_license_requires_policy_license
    {route : ConsequenceRoute W}
    (h : RouteLicensed W route) :
    W.integrated.PolicyLicensed route.use route.consequence := by
  exact h.right.left

theorem route_license_requires_each_authority_license
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (h : RouteLicensed W route)
    (hmem : recognizer ∈ route.recognizer_chain) :
    W.integrated.AuthorityLicensed route.use recognizer := by
  exact (h.right.right recognizer hmem).left

theorem route_license_requires_each_consequence_standing
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (h : RouteLicensed W route)
    (hmem : recognizer ∈ route.recognizer_chain) :
    W.ConsequenceStanding route.use recognizer route.consequence := by
  exact (h.right.right recognizer hmem).right

theorem unlicensed_recognizer_breaks_route_license
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (hmem : recognizer ∈ route.recognizer_chain)
    (hnot : Not (W.integrated.AuthorityLicensed route.use recognizer)) :
    Not (RouteLicensed W route) := by
  intro hroute
  exact hnot (route_license_requires_each_authority_license hroute hmem)

theorem no_consequence_standing_breaks_route_license
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (hmem : recognizer ∈ route.recognizer_chain)
    (hnot : Not (W.ConsequenceStanding route.use recognizer route.consequence)) :
    Not (RouteLicensed W route) := by
  intro hroute
  exact hnot (route_license_requires_each_consequence_standing hroute hmem)

theorem authority_and_policy_do_not_suffice_without_consequence_standing
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (hmem : recognizer ∈ route.recognizer_chain)
    (_hauthority : W.integrated.AuthorityLicensed route.use recognizer)
    (_hpolicy : W.integrated.PolicyLicensed route.use route.consequence)
    (hnot : Not (W.ConsequenceStanding route.use recognizer route.consequence)) :
    Not (RouteLicensed W route) := by
  exact no_consequence_standing_breaks_route_license hmem hnot

theorem route_license_yields_full_license_for_member
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (h : RouteLicensed W route)
    (hmem : recognizer ∈ route.recognizer_chain) :
    IntegratedWorld.FullyLicensed
      W.integrated
      route.system
      route.use
      recognizer
      route.consequence := by
  exact And.intro
    h.left
    (And.intro
      (route_license_requires_each_authority_license h hmem)
      h.right.left)

theorem drawn_without_consequence_standing_is_route_unauthorized
    {route : ConsequenceRoute W}
    {recognizer : W.integrated.Recognizer}
    (hdrawn : RouteConsequenceDrawn route)
    (hmem : recognizer ∈ route.recognizer_chain)
    (hnot : Not (W.ConsequenceStanding route.use recognizer route.consequence)) :
    RouteUnauthorized route := by
  exact And.intro hdrawn
    (no_consequence_standing_breaks_route_license hmem hnot)

theorem route_unauthorized_has_drawn_unlicensed
    {route : ConsequenceRoute W}
    (h : RouteUnauthorized route) :
    RouteConsequenceDrawn route /\
      Not (RouteLicensed W route) := by
  exact h

end RouteLicenseWorld

end FSST
/- END GENERATED MODULE: Core.RouteLicensed -/
/- BEGIN GENERATED MODULE: Core.CrossRecordRoute -/
/-
  Formal Symbolic Systems Theory - Cross-record route composition core.

  Status: candidate composition slice / stage 1 / do not promote.

  Source pressure:
    docs/formation/compiler_records/batch_trials/1o_cross_record_route_composition_records_v0.1.json

  Purpose:
    Encode the route-composition invariant discovered by the 1O batch:
    an upstream licensed route does not by itself license a downstream use.
    The downstream route must also be licensed, the upstream consequence must
    feed the downstream use, and required metadata must survive the transition.

  Non-claims:
    1. No domain-specific account of metadata adequacy.
    2. No proof that any real cross-record route is licensed.
    3. No production compiler/runtime claim.
-/


namespace FSST

universe u

structure CrossRecordWorld where
  routeWorld : RouteLicenseWorld
  FeedsDownstream :
    RouteLicenseWorld.ConsequenceRoute routeWorld ->
    RouteLicenseWorld.ConsequenceRoute routeWorld ->
    Prop
  MetadataPreserved :
    RouteLicenseWorld.ConsequenceRoute routeWorld ->
    RouteLicenseWorld.ConsequenceRoute routeWorld ->
    Prop

namespace CrossRecordWorld

variable (W : CrossRecordWorld)

structure CrossRecordRoute where
  upstream : RouteLicenseWorld.ConsequenceRoute W.routeWorld
  downstream : RouteLicenseWorld.ConsequenceRoute W.routeWorld

def CrossRecordLicensed
    (route : CrossRecordRoute W) : Prop :=
  RouteLicenseWorld.RouteLicensed W.routeWorld route.upstream /\
    RouteLicenseWorld.RouteLicensed W.routeWorld route.downstream /\
    W.FeedsDownstream route.upstream route.downstream /\
    W.MetadataPreserved route.upstream route.downstream

variable {W}

def CrossRecordConsequenceDrawn
    (route : CrossRecordRoute W) : Prop :=
  RouteLicenseWorld.RouteConsequenceDrawn route.downstream

def CrossRecordUnauthorized
    (route : CrossRecordRoute W) : Prop :=
  CrossRecordConsequenceDrawn route /\
    Not (CrossRecordLicensed W route)

theorem cross_record_license_requires_upstream_route
    {route : CrossRecordRoute W}
    (h : CrossRecordLicensed W route) :
    RouteLicenseWorld.RouteLicensed W.routeWorld route.upstream := by
  exact h.left

theorem cross_record_license_requires_downstream_route
    {route : CrossRecordRoute W}
    (h : CrossRecordLicensed W route) :
    RouteLicenseWorld.RouteLicensed W.routeWorld route.downstream := by
  exact h.right.left

theorem cross_record_license_requires_feed
    {route : CrossRecordRoute W}
    (h : CrossRecordLicensed W route) :
    W.FeedsDownstream route.upstream route.downstream := by
  exact h.right.right.left

theorem cross_record_license_requires_metadata
    {route : CrossRecordRoute W}
    (h : CrossRecordLicensed W route) :
    W.MetadataPreserved route.upstream route.downstream := by
  exact h.right.right.right

theorem upstream_license_does_not_suffice_without_downstream_license
    {route : CrossRecordRoute W}
    (_hup : RouteLicenseWorld.RouteLicensed W.routeWorld route.upstream)
    (hnot : Not (RouteLicenseWorld.RouteLicensed W.routeWorld route.downstream)) :
    Not (CrossRecordLicensed W route) := by
  intro hcross
  exact hnot (cross_record_license_requires_downstream_route hcross)

theorem route_licenses_do_not_suffice_without_feed
    {route : CrossRecordRoute W}
    (_hup : RouteLicenseWorld.RouteLicensed W.routeWorld route.upstream)
    (_hdown : RouteLicenseWorld.RouteLicensed W.routeWorld route.downstream)
    (hnot : Not (W.FeedsDownstream route.upstream route.downstream)) :
    Not (CrossRecordLicensed W route) := by
  intro hcross
  exact hnot (cross_record_license_requires_feed hcross)

theorem route_licenses_do_not_suffice_without_metadata
    {route : CrossRecordRoute W}
    (_hup : RouteLicenseWorld.RouteLicensed W.routeWorld route.upstream)
    (_hdown : RouteLicenseWorld.RouteLicensed W.routeWorld route.downstream)
    (hnot : Not (W.MetadataPreserved route.upstream route.downstream)) :
    Not (CrossRecordLicensed W route) := by
  intro hcross
  exact hnot (cross_record_license_requires_metadata hcross)

theorem downstream_drawn_without_metadata_is_cross_record_unauthorized
    {route : CrossRecordRoute W}
    (hdrawn : CrossRecordConsequenceDrawn route)
    (hnot : Not (W.MetadataPreserved route.upstream route.downstream)) :
    CrossRecordUnauthorized route := by
  exact And.intro hdrawn (by
    intro hcross
    exact hnot (cross_record_license_requires_metadata hcross))

theorem cross_record_unauthorized_has_drawn_unlicensed
    {route : CrossRecordRoute W}
    (h : CrossRecordUnauthorized route) :
    CrossRecordConsequenceDrawn route /\
      Not (CrossRecordLicensed W route) := by
  exact h

end CrossRecordWorld

end FSST
/- END GENERATED MODULE: Core.CrossRecordRoute -/
